CREATE TABLE IF NOT EXISTS GENRE (ID SERIAL PRIMARY KEY, TITLE VARCHAR(40) NOT NULL);

CREATE TABLE IF NOT EXISTS PERFORMER (ID SERIAL PRIMARY KEY, NAME VARCHAR(40) NOT NULL);

CREATE TABLE IF NOT EXISTS GENREPERFORMER (
	GENRE_ID INTEGER REFERENCES GENRE (ID),
	PERFORMER_ID INTEGER REFERENCES PERFORMER (ID),
	CONSTRAINT PK PRIMARY KEY (GENRE_ID, PERFORMER_ID)
);

CREATE TABLE IF NOT EXISTS ALBUM (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(40) NOT NULL,
	YEAR INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PERFORMERALBUM (
	PERFORMER_ID INTEGER REFERENCES PERFORMER (ID),
	ALBUM_ID INTEGER REFERENCES ALBUM (ID),
	CONSTRAINT PANDAK PRIMARY KEY (PERFORMER_ID, ALBUM_ID)
);

CREATE TABLE IF NOT EXISTS SONG (
	ID SERIAL PRIMARY KEY,
	ALBUM_ID INTEGER NOT NULL REFERENCES ALBUM (ID),
	TITLE VARCHAR(40) NOT NULL,
	DURATION INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS COLLECTION (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(40) NOT NULL,
	YEAR INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS COLLECTIONSONG (
	SONG_ID INTEGER NOT NULL REFERENCES SONG (ID),
	COLLECTION_ID INTEGER NOT NULL REFERENCES COLLECTION (ID),
	CONSTRAINT CANDSK PRIMARY KEY (SONG_ID, COLLECTION_ID)
);